// <auto-generated />
namespace PassionProjectChariity_s2022.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fund : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fund));
        
        string IMigrationMetadata.Id
        {
            get { return "202206051111545_fund"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
