// <auto-generated />
namespace PassionProjectChariity_s2022.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class donationfund : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(donationfund));
        
        string IMigrationMetadata.Id
        {
            get { return "202206051124549_donation-fund"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
